// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-QCCiyfOas7YHsQ4BXrjLHvZQbJDB3FI',
    appId: '1:909820053313:web:57671a0429ec063a8243c0',
    messagingSenderId: '909820053313',
    projectId: 'euphoric-solutions',
    authDomain: 'euphoric-solutions.firebaseapp.com',
    storageBucket: 'euphoric-solutions.appspot.com',
    measurementId: 'G-BEFCHHR490',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEB1Za0eQCHVbYJFUlftn9bjYgTjh_Z5g',
    appId: '1:909820053313:android:dfeff08890512d598243c0',
    messagingSenderId: '909820053313',
    projectId: 'euphoric-solutions',
    storageBucket: 'euphoric-solutions.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc7snR8LwiuouLJEigthgRNBkJEQ8Xqn8',
    appId: '1:909820053313:ios:d7a32f2d16650e078243c0',
    messagingSenderId: '909820053313',
    projectId: 'euphoric-solutions',
    storageBucket: 'euphoric-solutions.appspot.com',
    iosBundleId: 'com.example.euphoric',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc7snR8LwiuouLJEigthgRNBkJEQ8Xqn8',
    appId: '1:909820053313:ios:d7a32f2d16650e078243c0',
    messagingSenderId: '909820053313',
    projectId: 'euphoric-solutions',
    storageBucket: 'euphoric-solutions.appspot.com',
    iosBundleId: 'com.example.euphoric',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-QCCiyfOas7YHsQ4BXrjLHvZQbJDB3FI',
    appId: '1:909820053313:web:e16cf79fc975fc9c8243c0',
    messagingSenderId: '909820053313',
    projectId: 'euphoric-solutions',
    authDomain: 'euphoric-solutions.firebaseapp.com',
    storageBucket: 'euphoric-solutions.appspot.com',
    measurementId: 'G-HFMT016H5E',
  );
}
